### ISSUE TITLE
changelog --release major resulted in `major` token being set and vmajor tag

### ISSUE THREAD

**Issue by vvo** [defunctzombie/changelog#13]
What the? :)

**Comment by defunctzombie** [comment]
? I don't understand the issue. What did you do vs what did you expect to happen?

**Comment by vvo** [comment]
I did `changelog --release major` and I was expecting to see the version bump from 2 to 3. Instead I got a version labelled "vmajor".

`changelog --release minor` is ok thought.

Better?

**Comment by defunctzombie** [comment]
hm. I am pretty certain I have used `major` a few times now and it has worked. The relevant code for this is here: https://github.com/defunctzombie/changelog/blob/master/bin/changelog#L103-L109

Are you able to reproduce on a test project consistently?

**Comment by vvo** [comment]
I think that's since the switch to node v4 :) I am on node v4 that must be it. Patch fail too, like minor I guess.

**Comment by defunctzombie** [comment]
Would love to know how switching to v4 would cause this?! That is something magical.

**Comment by defunctzombie** [comment]
I just tried it in an test project and `--release major` worked. If you can reproduce please post the steps.

**Comment by vvo** [comment]
re-tried and it worked, strannnge
